# Generated by Django 4.2.1 on 2023-06-25 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0002_alter_usuario_options_alter_usuario_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='esBarbero',
            field=models.BooleanField(default=False),
        ),
    ]
