# Generated by Django 4.2.1 on 2023-06-15 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
        ('Turnos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='profesional',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='turno_profesional', to='Usuarios.usuario'),
        ),
    ]
