# Generated by Django 4.2.1 on 2023-06-25 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Turnos', '0002_turno_profesional'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turno',
            old_name='usuario',
            new_name='cliente',
        ),
    ]
