# Generated by Django 4.2.1 on 2023-06-25 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Turnos', '0003_rename_usuario_turno_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
